INSERT INTO `lasalle`.`cat_especialidad` (`idcat_especialidad`, `especialidad_nombre`, `especialidad_fecha`) VALUES ('1', 'Ingenieria de software', now());
INSERT INTO `lasalle`.`cat_especialidad` (`idcat_especialidad`, `especialidad_nombre`, `especialidad_fecha`) VALUES ('2', 'Psicología', now());
INSERT INTO `lasalle`.`cat_especialidad` (`idcat_especialidad`, `especialidad_nombre`, `especialidad_fecha`) VALUES ('3', 'Educación', now());
INSERT INTO `lasalle`.`cat_especialidad` (`idcat_especialidad`, `especialidad_nombre`, `especialidad_fecha`) VALUES ('4', 'Mecatronica', now());
INSERT INTO `lasalle`.`cat_especialidad` (`idcat_especialidad`, `especialidad_nombre`, `especialidad_fecha`) VALUES ('5', 'Derecho', now());
INSERT INTO `lasalle`.`cat_especialidad` (`idcat_especialidad`, `especialidad_nombre`, `especialidad_fecha`) VALUES ('6', 'Maestría en peritajes', now());
INSERT INTO `lasalle`.`cat_especialidad` (`idcat_especialidad`, `especialidad_nombre`, `especialidad_fecha`) VALUES ('7', 'Maestría en educación especial', now());
INSERT INTO `lasalle`.`cat_especialidad` (`idcat_especialidad`, `especialidad_nombre`, `especialidad_fecha`) VALUES ('8', 'Maestría en educación especial', now());
INSERT INTO `lasalle`.`cat_especialidad` (`idcat_especialidad`, `especialidad_nombre`, `especialidad_fecha`) VALUES ('9', 'Doctorado en investigación', now());
INSERT INTO `lasalle`.`cat_especialidad` (`idcat_especialidad`, `especialidad_nombre`, `especialidad_fecha`) VALUES ('10', 'Doctorado en tecnologías', now());
